version: "3"
services:
  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - /mnt/hgfs/www/opt/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  redis:
    build: ./redis
    ports:
      - "6379:6379"

  php:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "redis"
    volumes:
      - /mnt/hgfs/www/opt:/opt

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - /mnt/hgfs/www/opt:/opt