FROM python:3.7.2

RUN apt-get update && apt-get install -y procps vim

#COPY requirements.txt ./
#RUN pip install --no-cache-dir -r requirements.txt

#CMD [ "python", "./your-daemon-or-script.py" ]

WORKDIR /opt
VOLUME ["/opt"]